# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e590773cab5489f075d1e3f3c7f9bd0ea836d3c45a77996f0d38cca34f651d003645067b14b3a756c1cea1ba6757c4e1990ed58078198493ae2171ebcf43554

test:
  secret_key_base: ed9e57ef219ae7052571e7f07c95532ae0870fe40059e6014ca8184c7ab92218ed8a50a4941f3b4680028bcdd431719f0405cd6c187986fa5b41bc8a1aa3cf40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
