password:
  minimum: 6
email:
  maximum: 255
username:
  maximum: 50
paginate:
  per_page: 10
gravatar_option:
  size: 80
gravatar_user:
  size: 50
page:
  per_page: 5
gravatar:
  size1: 80
  size2: 50
post:
  maximum: 200
  size: 50
